import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourcePath = resolve(root, 'data.dat')
const cleanPath = resolve(root, 'data/love-lines.txt')
const generatedPath = resolve(root, 'packages/dataset/src/generated.ts')

const source = await readFile(sourcePath)
const decoded = new TextDecoder('utf-8', { fatal: true }).decode(source)

const lines = decoded
  .replace(/\r\n?/g, '\n')
  .split('\n')
  .map((line) => line.replace(/[\u200B\u200C\u200D\u2060\uFEFF]/g, '').trim())
  .filter(Boolean)

const uniqueLines = [...new Set(lines)]
if (uniqueLines.length !== lines.length) {
  throw new Error(`Data contains ${lines.length - uniqueLines.length} duplicate line(s)`)
}

const entries = uniqueLines.map((text) => ({
  id: `line_${createHash('sha256').update(text).digest('hex').slice(0, 12)}`,
  text,
}))
const datasetVersion = createHash('sha256')
  .update(uniqueLines.join('\n'))
  .digest('hex')
  .slice(0, 12)

const generated = `// Generated by scripts/prepare-data.mjs. Do not edit by hand.\n` +
  `export interface LoveLine {\n  readonly id: string\n  readonly text: string\n}\n\n` +
  `export const datasetVersion = ${JSON.stringify(datasetVersion)} as const\n\n` +
  `export const loveLines: readonly LoveLine[] = ${JSON.stringify(entries, null, 2)}\n`

await mkdir(dirname(cleanPath), { recursive: true })
await mkdir(dirname(generatedPath), { recursive: true })
await writeFile(cleanPath, `${uniqueLines.join('\n')}\n`, 'utf8')
await writeFile(generatedPath, generated, 'utf8')

console.log(`Prepared ${entries.length} love lines (dataset ${datasetVersion})`)
